data_path: ./.data/train/train_ratings.csv
saved_path: ./.saved/CDAE.pt
submission_path: ./.saved/submission_CDAE.csv
params:
  seed: 42
  learning_rate: 0.001
  batch_size: 16
  num_epochs: 100
  num_hidden_units: 50
  corruption_ratio: 0.5
  valid_samples: 10
  num_workers: 4
